# Project Title: Loan Status Prediction

**1.Project Title**:Loan Approval Prediction System

**Project Type**:Classification

**Contribution**:Individual

**2.Objective**

The objective of this project is to build a machine learning model that predicts whether a loan application will be approved or rejected based on applicant details such as income, credit history, loan amount, and other demographic features.

**3.Dataset**

The dataset contains 614 records with multiple features describing applicant information and loan details.
Important columns in the dataset include:
Gender
Married
Dependents
Applicant Income
Coapplicant Income
Loan Amount
Loan Amount Term
Credit History
Property Area

**Target Variable**

Loan_Status (Y/N)

Y → Loan Approved
N → Loan Rejected

In [1]:
import numpy as np
import pandas as pd
df= pd.read_csv('loan_data.csv')
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [2]:
print(df.shape)

(614, 13)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [5]:
df.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

**4. Data Preprocessing**

In [6]:
df1=df.copy(deep=True)

In [7]:
df1.isna().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

Removing unnecessary columns

The following columns were removed because they were not useful for prediction:


1.   Married
2.   Education
3.   Self_Employed

In [8]:
df1.drop(columns=['Married','Education','Self_Employed'], inplace=True)
df1.head()

,Loan_ID,Gender,Dependents,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,0,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,1,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,0,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,0,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,0,6000,0.0,141.0,360.0,1.0,Urban,Y

Convert the object type columns into the integer type Data:

1.   Loan_ID
2.   Gender
3.   Property_Area
4.   Loan_Status

In [9]:
df1['Loan_ID'] = df1['Loan_ID'].str.replace('LP', '').astype(int)

In [27]:
df1['Gender'].value_counts()

Gender
Male      502
Female    112
Name: count, dtype: int64

In [31]:
mapping={"Male":1, "Female":0}
df1["Gender"]=df1 ['Gender'].map(mapping)

In [32]:
df1['Property_Area'].value_counts()

Property_Area
Semiurban    233
Urban        202
Rural        179
Name: count, dtype: int64

In [33]:
mapping={"Semiurban":2, "Urban":1,"Rural":0}
df1 ['Property_Area']=df1 ['Property_Area'].map(mapping)

In [34]:
df1['Loan_Status'].value_counts()

Loan_Status
Y    422
N    192
Name: count, dtype: int64

In [35]:
mapping={"Y":1, "N":0}
df1 ['Loan_Status']=df1 ['Loan_Status'].map(mapping)

Handling missing values

Missing values in the following columns were filled using the mean value:


1.   Gender
2.   Dependents
3.   LoanAmount
4.   Loan_Amount_Term
5.   Credit_History

In [18]:
df1.isna().sum()

Loan_ID               0
Gender               13
Dependents           15
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [36]:
df1['Gender'].fillna(df1['Gender'].mode()[0], inplace=True)
df1.head(25)

/tmp/ipykernel_2324/2524895309.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Gender'].fillna(df1['Gender'].mode()[0], inplace=True)

,Loan_ID,Gender,Dependents,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,1002,1,0,5849,0.0,NaN,360.0,1.0,1,1
1,1003,1,1,4583,1508.0,128.0,360.0,1.0,0,0
2,1005,1,0,3000,0.0,66.0,360.0,1.0,1,1
3,1006,1,0,2583,2358.0,120.0,360.0,1.0,1,1
4,1008,1,0,6000,0.0,141.0,360.0,1.0,1,1
5,1011,1,2,5417,4196.0,267.0,360.0,1.0,1,1
6,1013,1,0,2333,1516.0,95.0,360.0,1.0,1,1
7,1014,1,3+,3036,2504.0,158.0,360.0,0.0,2,0
8,1018,1,2,4006,1526.0,168.0,360.0,1.0,1,1
9,1020,1,1,12841,10968.0,349.0,360.0,1.0,2,0
10,1024,1,2,3200,700.0,70.0,360.0,1.0,1,1
11,1027,1,2,2500,1840.0,109.0,360.0,1.0,1,1
12,1028,1,2,3073,8106.0,200.0,360.0,1.0,1,1
13,1029,1,0,1853,2840.0,114.0,360.0,1.0,0,0
14,1030,1,2,1299,1086.0,17.0,120.0,1.0,1,1
15,1032,1,0,4950,0.0,125.0,360.0,1.0,1,1
16,1034,1,1,3596,0.0,100.0,240.0,NaN,1,1
17,1036,0,0,3510,0.0,76.0,360.0,0.0,1,0
18,1038,1,0,4887,0.0,133.0,360.0,1.0,0,0
19,1041,1,0,2600,3500.0,115.0,NaN,1.0,1,1
20,1043,1,0,7660,0.0,104.0,360.0,0.0,1,0
21,1046,1,1,5955,5625.0,315.0,360.0,1.0,1,1
22,1047,1,0,2600,1911.0,116.0,360.0,0.0,2,0
23,1050,1,2,3365,1917.0,112.0,360.0,0.0,0,0
24,1052,1,1,3717,2925.0,151.0,360.0,NaN,2,0

In [37]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    int64
 1   Gender             614 non-null    int64
 2   Dependents         599 non-null    object
 3   ApplicantIncome    614 non-null    int64
 4   CoapplicantIncome  614 non-null    float64
 5   LoanAmount         592 non-null    float64
 6   Loan_Amount_Term   600 non-null    float64
 7   Credit_History     564 non-null    float64
 8   Property_Area      614 non-null    int64
 9   Loan_Status        614 non-null    int64
dtypes: float64(4), int64(5), object(1)
memory usage: 48.1+ KB

In [38]:
df1['Dependents'].value_counts()

Dependents
0     345
1     102
2     101
3+     51
Name: count, dtype: int64

In [43]:
df1['Dependents'].fillna(df1['Dependents'].mode()[0], inplace=True)

In [45]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    int64
 1   Gender             614 non-null    int64
 2   Dependents         614 non-null    int64
 3   ApplicantIncome    614 non-null    int64
 4   CoapplicantIncome  614 non-null    float64
 5   LoanAmount         592 non-null    float64
 6   Loan_Amount_Term   600 non-null    float64
 7   Credit_History     564 non-null    float64
 8   Property_Area      614 non-null    int64
 9   Loan_Status        614 non-null    int64
dtypes: float64(4), int64(6)
memory usage: 48.1 KB

In [44]:
df1['Dependents'] = df1['Dependents'].replace('3+', 3).astype(int)

In [46]:
df1['LoanAmount'].fillna(df1['LoanAmount'].median(), inplace=True)
df1['Loan_Amount_Term'].fillna(df1['Loan_Amount_Term'].median(), inplace=True)

/tmp/ipykernel_2324/2862253280.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['LoanAmount'].fillna(df1['LoanAmount'].median(), inplace=True)
/tmp/ipykernel_2324/2862253280.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Loan_Amount_Term'].fillna(df1['Loan_Amount_Term'].median(), inplace=True)

In [47]:
df1.isna().sum()

Loan_ID               0
Gender                0
Dependents            0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term      0
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [50]:
df1['Credit_History'].fillna(df1['Credit_History'].mode()[0], inplace=True)

/tmp/ipykernel_2324/3055299793.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Credit_History'].fillna(df1['Credit_History'].mode()[0], inplace=True)

In [51]:
df1.isna().sum()

Loan_ID              0
Gender               0
Dependents           0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

5. Feature and Target Selection
Features (Input Variables)

1.   Gender
2.   Dependents
3.   Applicant Income
4.   Coapplicant Income
5.   Loan Amount
6.   Loan Amount Term
7.   Credit History
8.   Property Area

In [65]:
x=df1.drop(columns=['Loan_ID','Loan_Status'])
y=df1['Loan_Status']

**6.Model Training**

The dataset was split into training and testing sets.

Training data: 80%

Testing data: 20%

Two machine learning models were trained:

Logistic Regression

Random Forest Classifier

In [66]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y, test_size=0.2, random_state=2)

**7.Model Evaluation**


The model was evaluated using **accuracy, confusion matrix, and classification report**.

Random Forest performed better than Logistic Regression and achieved about **74% accuracy**. The model predicts loan approval cases more accurately than rejection cases.

In [67]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [71]:
model = LogisticRegression()

In [82]:
from sklearn.ensemble import RandomForestClassifier
rf= RandomForestClassifier()
rf.fit(x_train, y_train)

RandomForestClassifier()

In [85]:
rf = RandomForestClassifier()
rf.fit(x_train, y_train)

RandomForestClassifier()

In [76]:
y_pred = rf.predict(x_test)

In [77]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.7398373983739838

In [78]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[15, 24],
       [ 8, 76]])

In [79]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.65      0.38      0.48        39
           1       0.76      0.90      0.83        84

    accuracy                           0.74       123
   macro avg       0.71      0.64      0.65       123
weighted avg       0.73      0.74      0.72       123

**8.Prediction**

A new loan application was given to the model to predict whether the loan will be approved or not.

Example input:

Gender: Male

Dependents: 0

Applicant Income: 5000

Coapplicant Income: 2000

Loan Amount: 150

Loan Amount Term: 360

Credit History: 1

Property Area: Urban

The model predicted whether the loan would be approved (1) or rejected (0) based on these details.

In [87]:
x_new = pd.DataFrame([[1100,1,0,5859,0,361,1,1]],
                     columns=x.columns)

rf.predict(x_new)

array([0])

In [88]:
x_new = pd.DataFrame([[1,0,5000,2000,150,360,1,2]],
                     columns=x.columns)

rf.predict(x_new)

array([1])

**9. Tools and Libraries Used**
Python
NumPy
Pandas
Matplotlib
Scikit-learn


**10.Conclusion**

In this project, a machine learning model was developed to predict whether a loan will be approved or not based on applicant details. Data preprocessing, feature encoding, and classification techniques were applied to improve model performance. The Random Forest Classifier provided better accuracy compared to Logistic Regression.

In [89]:
import gradio as gr
import pandas as pd

# Assuming 'rf' (RandomForestClassifier model) and 'x' (DataFrame of features)
# are already defined in the environment from previous executed cells.

def predict_loan_status_adjusted(gender, dependents_str, applicant_income, coapplicant_income,
                        loan_amount, loan_amount_term, credit_history, property_area):

    # Convert '3+' to integer 3 for 'Dependents'
    dependents = int(dependents_str.replace('+', ''))

    # Create a DataFrame from the inputs, ensuring column order matches x.columns
    input_data = pd.DataFrame([[gender, dependents, applicant_income, coapplicant_income,
                                loan_amount, loan_amount_term, credit_history, property_area]],
                              columns=x.columns)

    prediction = rf.predict(input_data)

    if prediction[0] == 1:
        return "Loan Approved ✅"
    else:
        return "Loan Denied ❌"

# Define Gradio inputs based on feature types and their mappings
inputs = [
    gr.Radio(choices=[("Male", 1), ("Female", 0)], label="Gender", value=1), # Default to Male
    gr.Radio(choices=["0", "1", "2", "3+"], label="Dependents", value="0"), # Default to 0 dependents
    gr.Number(label="Applicant Income", minimum=0, value=5000),
    gr.Number(label="Coapplicant Income", minimum=0.0, value=2000.0),
    gr.Number(label="Loan Amount (in thousands)", minimum=0.0, value=150.0),
    gr.Number(label="Loan Amount Term (in months)", minimum=0.0, value=360.0),
    gr.Radio(choices=[("Yes", 1.0), ("No", 0.0)], label="Credit History", value=1.0), # Default to Yes
    gr.Radio(choices=[("Semiurban", 2), ("Urban", 1), ("Rural", 0)], label="Property Area", value=2) # Default to Semiurban
]

# Define the output component
output = gr.Label()

# Define custom CSS for a visually appealing interface
css = """
body {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    background-color: #e0f2f7; /* Light blue background */
}
.gradio-container {
    max-width: 900px;
    margin: 40px auto;
    border-radius: 20px;
    box-shadow: 0 15px 40px rgba(0, 0, 0, 0.15);
    background-color: #ffffff;
    border: 1px solid #b3e5fc;
}
.gr-button.primary {
    background-color: #0288d1; /* Deep Sky Blue */
    color: white;
    border-radius: 10px;
    padding: 12px 25px;
    font-size: 17px;
    font-weight: bold;
    transition: background-color 0.3s ease;
}
.gr-button.primary:hover {
    background-color: #0277bd; /* Slightly darker blue on hover */
}
.gr-label {
    font-size: 28px;
    font-weight: bold;
    color: #263238; /* Dark grey text */
    text-align: center;
    padding: 25px;
    border-top: 2px solid #e0f2f7;
    background-color: #f5f5f5;
    border-bottom-left-radius: 18px;
    border-bottom-right-radius: 18px;
}
h1 {
    color: #01579b; /* Darker blue for main title */
    text-align: center;
    font-size: 38px;
    margin-bottom: 15px;
    text-shadow: 1px 1px 2px rgba(0,0,0,0.05);
}
h3 {
    color: #455a64; /* Medium grey for description */
    text-align: center;
    font-size: 19px;
    margin-bottom: 35px;
}
.gr-radio-group {
    font-weight: 500;
    color: #37474f;
}
"""

# Create the Gradio interface
iface = gr.Interface(
    fn=predict_loan_status_adjusted,
    inputs=inputs,
    outputs=output,
    title="<span style='color:#01579b;'>🏦 Loan Approval Predictor 📈</span>", # Title with color
    description="<h3>Input the applicant's details below to get an instant prediction on their loan approval status.</h3>", # Description with styling
    css=css,
    theme=gr.themes.Soft() # Use the 'Soft' theme for a modern look
)

# Launch the interface
iface.launch(share=True)

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://abcf98ee1c1c027233.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)